In [2]:
distance = [10,15,17,26]
time = [0.3,0.47,0.55,1.2]

In [3]:
speed = distance / time 

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
import numpy as np

In [5]:
np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance/np_time
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [6]:
#first NumPy array 
first_numpy_array = np.array([1,2,3,4,5])


In [9]:
#print first array
print (first_numpy_array)

[1 2 3 4 5]


In [60]:
#array with zeros
array_with_zeros = np.zeros((7,2))
array_with_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
#array with ones

In [24]:
#empty arrays for random numbers 
array_with_empty = np.empty((2,4))
array_with_empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.22646744e-307],
       [2.67017691e-306, 1.42413555e-306, 1.78019082e-306,
        1.37959740e-306]])

In [37]:
#array with arange method
np_arange = np.arange(24)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [39]:
#reshape to change / reorder array
np_arange.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [71]:
#linspace for lineraly equal spaced data elements 1 - first, 10 - last number, 100 - number of equidistant elements in total. 
np_linspace = np.linspace (1,10,20)
print (np_linspace)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [50]:
# one d array
OneD_array = np.arange(12)
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
# 2 d array
TwoD_array = OneD_array.reshape(3,4)
print (TwoD_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
#3 d array
ThreeD_array = np.arange(12).reshape(1,6,2)
print (ThreeD_array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]]


In [66]:
# new array for dim, shape, size and type analysis 
nd_array = np. array([['SRH','KKR','RPSG'],['CSK','LSG','RR']])
nd_array.ndim
                      
                    

2

In [67]:
nd_array.size

6

In [68]:
nd_array.shape

(2, 3)

In [70]:
nd_array.dtype

dtype('<U4')

In [52]:
# adding two arrays / vector addition
import numpy as np
match_one_scores = np.array([12,24,45,101])
match_two_scores = np.array([40,124,3,12])
total_scores = match_one_scores + match_two_scores
print (total_scores)

[ 52 148  48 113]


In [9]:
import numpy as np


In [51]:
#add
np.add(23,34)

57

In [45]:
#subtract
np.subtract(23,34)

-11

In [12]:
#multiply
np.multiply(23,34)

782

In [13]:
#divide and add
np.divide(np.multiply(23,34),34)

23.0

In [21]:
#yearly mean
np_yearly= np.array([12,23,4])*3
np_yearly

array([36, 69, 12])

In [22]:
sum(np_yearly)

117

In [29]:
#numpy for comparisons, always use square brackets 

np_yearly[np_yearly>35]

array([36, 69])

In [38]:
# for data not equal to a value , use of exclamation mark '!' for not equal to
np_yearly[np_yearly != 36]

array([69, 12])

In [43]:
# for AND logical test 
np.logical_and(np_yearly > 20, np_yearly < 70)

array([ True,  True, False])

In [53]:
# for not satisfying
np.logical_not(np_yearly >60)

array([ True, False,  True])

In [57]:
#accessing specific arrays
trials = np.array([[10,20,34,56],[34,5,33,23]])
first_trial = trials[0]
first_trial

array([10, 20, 34, 56])

In [59]:
second_trial= trials[1]
second_trial

array([34,  5, 33, 23])

In [61]:
first_cyclist_all_trials = trials [:,0]
first_cyclist_all_trials

array([10, 34])

In [8]:
import numpy as np
trials = np.array([[10,20,34,56],[34,5,33,23]])
second_cyclist_third_trial= trials [1,3]
second_cyclist_third_trial

23

In [11]:
#slicing
both_trial_data = trials[:,0:2]
both_trial_data 

array([[10, 20],
       [34,  5]])

In [21]:
# using iterations for going through each element in data
trials = np.array([[10,20,34,56],[34,5,33,23]])
for iterate_trials in trials:
    print(iterate_trials)

[10 20 34 56]
[34  5 33 23]


In [25]:
#using boolean for normalisation 
test_scores = np.array([[23,43,54,65],[54,87,45,78]])
passing_score = test_scores > 30
passing_score

array([[False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
test_scores[passing_score]

array([43, 54, 65, 54, 87, 45, 78])

In [23]:
for iterate_both_trial_data in both_trial_data:
    print(iterate_both_trial_data)


[10 20]
[34  5]


In [39]:
#exp
np_sqrt = np.sqrt([2,4,3])
np_sqrt

array([1.41421356, 2.        , 1.73205081])

In [42]:
from numpy import pi
np.cos(0)

1.0

In [43]:
np.sin(pi/2)

1.0

In [48]:
import numpy as np
result = np.exp([0,1,5])

TypeError: 'list' object is not callable

In [52]:

np.floor([1.4,5.2,7.77,-1.9])

array([ 1.,  5.,  7., -2.])

In [59]:
bowler_wickets_match_one = np.array([3,2,4,1])
bowler_wickets_match_two = np.array([2,3,2,3])
bowler_wickets = bowler_wickets_match_one + bowler_wickets_match_two
bowler_wickets

array([5, 5, 6, 4])

In [63]:
bowler_wickets_together = np.array([[3,2,4,1],[2,3,2,3]])

bowler_wickets_together.ravel()

array([3, 2, 4, 1, 2, 3, 2, 3])

In [62]:
trials = np.array([[10,20,34,56],[34,5,33,23]])

In [58]:
trials.ravel()

array([10, 20, 34, 56, 34,  5, 33, 23])

In [64]:
bowler_wickets_together.reshape(2,4)

array([[3, 2, 4, 1],
       [2, 3, 2, 3]])

In [66]:
bowler_wickets_together.resize(4,2)

In [67]:
bowler_wickets_together

array([[3, 2],
       [4, 1],
       [2, 3],
       [2, 3]])

In [68]:
bowler_wickets_together.reshape(4,2)

array([[3, 2],
       [4, 1],
       [2, 3],
       [2, 3]])

In [69]:
# splits the array into two
np.hsplit(bowler_wickets_together,2)

[array([[3],
        [4],
        [2],
        [2]]),
 array([[2],
        [1],
        [3],
        [3]])]

In [73]:
bowler_wickets_match_one = np.array([3,2,4,1])
bowler_wickets_match_two = np.array([2,3,2,3])
np.hstack((bowler_wickets_match_one,bowler_wickets_match_two))

array([3, 2, 4, 1, 2, 3, 2, 3])

In [74]:
one = np.array([86,77,32])
two = np.array([31,45,6])
one*two


array([2666, 3465,  192])

In [75]:
scalar_c= 3
one*scalar_c

array([258, 231,  96])

In [94]:
one = np.array([86,77,32])
two = np.array([31,45,6])

total = np.array ([[86,77,32],[31,45,6]])


In [95]:
total

array([[86, 77, 32],
       [31, 45,  6]])

In [96]:
total.transpose()

array([[86, 31],
       [77, 45],
       [32,  6]])

In [103]:
inverse = np.array ([[86,77],[31,45]])
np.linalg.inv(inverse)

array([[ 0.0303439 , -0.05192178],
       [-0.02090357,  0.05799056]])

In [104]:
np.trace(inverse)

131

In [106]:
86+45

131

In [ ]:
List of countries:

'Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'


GDP values for each country:

2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605

In [111]:
import numpy as np

In [112]:
2+45

47

In [113]:
np.trace(inverse)

131

In [115]:
np.hsplit(bowler_wickets_together,1)

[array([[3, 2],
        [4, 1],
        [2, 3],
        [2, 3]])]

In [119]:
c_name = np.array([
'Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'])
c_gdp =np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])
name_GDP_match = np.array([['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'
                        ],[2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605]])
name_GDP_match

array([['Algeria', 'Angola', 'Argentina', 'Australia', 'Austria',
        'Bahamas', 'Bangladesh', 'Belarus', 'Belgium', 'Bhutan',
        'Brazil', 'Bulgaria', 'Cambodia', 'Cameroon', 'Chile', 'China',
        'Colombia', 'Cyprus', 'Denmark', 'El Salvador', 'Estonia',
        'Ethiopia', 'Fiji', 'Finland', 'France', 'Georgia', 'Ghana',
        'Grenada', 'Guinea', 'Haiti', 'Honduras', 'Hungary', 'India',
        'Indonesia', 'Ireland', 'Italy', 'Japan', 'Kenya', 'South Korea',
        'Liberia', 'Malaysia', 'Mexico', 'Morocco', 'Nepal',
        'New Zealand', 'Norway', 'Pakistan', 'Peru', 'Qatar', 'Russia',
        'Singapore', 'South Africa', 'Spain', 'Sweden', 'Switzerland',
        'Thailand', 'United Arab Emirates', 'United Kingdom',
        'United States', 'Uruguay', 'Venezuela', 'Vietnam', 'Zimbabwe'],
       ['2255.225482', '629.9553062', '11601.63022', '25306.82494',
        '27266.40335', '19466.99052', '588.3691778', '2890.345675',
        '24733.62696', '1445.760002', '480

In [117]:
name_GDP_match.transpose()

array([['Algeria', '2255.225482'],
       ['Angola', '629.9553062'],
       ['Argentina', '11601.63022'],
       ['Australia', '25306.82494'],
       ['Austria', '27266.40335'],
       ['Bahamas', '19466.99052'],
       ['Bangladesh', '588.3691778'],
       ['Belarus', '2890.345675'],
       ['Belgium', '24733.62696'],
       ['Bhutan', '1445.760002'],
       ['Brazil', '4803.398244'],
       ['Bulgaria', '2618.876037'],
       ['Cambodia', '590.4521124'],
       ['Cameroon', '665.7982328'],
       ['Chile', '7122.938458'],
       ['China', '2639.54156'],
       ['Colombia', '3362.4656'],
       ['Cyprus', '15378.16704'],
       ['Denmark', '30860.12808'],
       ['El Salvador', '2579.115607'],
       ['Estonia', '6525.541272'],
       ['Ethiopia', '229.6769525'],
       ['Fiji', '2242.689259'],
       ['Finland', '27570.4852'],
       ['France', '23016.84778'],
       ['Georgia', '1334.646773'],
       ['Ghana', '402.6953275'],
       ['Grenada', '6047.200797'],
       ['Guinea', '394

In [133]:
c_gdp[c_gdp>40034.85063]

array([], dtype=float64)

In [155]:
import numpy as np
max_gdp_per_capita = c_gdp.argmax()

In [136]:
c_name_with_max_gdp = c_name[max_gdp_per_capita]
c_name_with_max_gdp

'Norway'

In [137]:
min_gdp_per_capita = c_gdp.argmin()

In [138]:
c_name_with_min_gdp = c_name[min_gdp_per_capita]
c_name_with_min_gdp

'Ethiopia'

In [144]:
#important code
for country in c_name :
    print ('ecalculating country {}'.format(country))

ecalculating country Algeria
ecalculating country Angola
ecalculating country Argentina
ecalculating country Australia
ecalculating country Austria
ecalculating country Bahamas
ecalculating country Bangladesh
ecalculating country Belarus
ecalculating country Belgium
ecalculating country Bhutan
ecalculating country Brazil
ecalculating country Bulgaria
ecalculating country Cambodia
ecalculating country Cameroon
ecalculating country Chile
ecalculating country China
ecalculating country Colombia
ecalculating country Cyprus
ecalculating country Denmark
ecalculating country El Salvador
ecalculating country Estonia
ecalculating country Ethiopia
ecalculating country Fiji
ecalculating country Finland
ecalculating country France
ecalculating country Georgia
ecalculating country Ghana
ecalculating country Grenada
ecalculating country Guinea
ecalculating country Haiti
ecalculating country Honduras
ecalculating country Hungary
ecalculating country India
ecalculating country Indonesia
ecalculating c

In [154]:
#getting twp variables together - work out the mistake
for i in range(len(c_gdp)):
    country = c_name[i]
    GDP = c_gdp[i]
    print ('{} is having a per capita GDP of {}'.format(country, GDP ))
    
    

Algeria is having a per capita GDP of 2255.225482
Angola is having a per capita GDP of 629.9553062
Argentina is having a per capita GDP of 11601.63022
Australia is having a per capita GDP of 25306.82494
Austria is having a per capita GDP of 27266.40335
Bahamas is having a per capita GDP of 19466.99052
Bangladesh is having a per capita GDP of 588.3691778
Belarus is having a per capita GDP of 2890.345675
Belgium is having a per capita GDP of 24733.62696
Bhutan is having a per capita GDP of 1445.760002
Brazil is having a per capita GDP of 4803.398244
Bulgaria is having a per capita GDP of 2618.876037
Cambodia is having a per capita GDP of 590.4521124
Cameroon is having a per capita GDP of 665.7982328
Chile is having a per capita GDP of 7122.938458
China is having a per capita GDP of 2639.54156
Colombia is having a per capita GDP of 3362.4656
Cyprus is having a per capita GDP of 15378.16704
Denmark is having a per capita GDP of 30860.12808
El Salvador is having a per capita GDP of 2579.115

In [160]:
import numpy as np
print(c_gdp.max())
print(c_gdp.min())
print(c_gdp.mean())
print(c_gdp.std())
print(c_gdp.sum())

40034.85063
229.6769525
11289.409271639683
12743.828910617945
711232.7841133


In [169]:
print('Minimum GDP of a country is', c_gdp.min())

Minimum GDP of a country is 229.6769525


In [193]:
# country to win maximum gold medals
import numpy as np
country = np.array(['Great Britain',
'China', 
'Russia',
'United States',
'Korea',
'Japan',
'Germany'])
gold_medals = np.array([29,
38,
24,
46,
13,
7,
11])
max_gold_medals = gold_medals.argmax()
country_with_max_gold_medals = country[max_gold_medals]

print (country_with_max_gold_medals)


United States


In [194]:
#Boolean indexing technique
gold_medals_more_than_twenty = (gold_medals>20)
country_with_criteria = country[gold_medals_more_than_twenty]
print (country_with_criteria)

['Great Britain' 'China' 'Russia' 'United States']


In [192]:
#medal tally 
import numpy as np
country = np.array(['Great Britain',
'China', 
'Russia',
'United States',
'Korea',
'Japan',
'Germany'])
gold_medals = np.array([29,
38,
24,
46,
13,
7,
11])
silver_medals = np.array ([17,
28,
25,
28,
8,
14,
11])
bronze_medals = np.array([19,
22,
32,
29,
7,
17,
14])
medal_tally = [country, gold_medals, silver_medals, bronze_medals]
medal_tally


[array(['Great Britain', 'China', 'Russia', 'United States', 'Korea',
        'Japan', 'Germany'], dtype='<U13'),
 array([29, 38, 24, 46, 13,  7, 11]),
 array([17, 28, 25, 28,  8, 14, 11]),
 array([19, 22, 32, 29,  7, 17, 14])]

AttributeError: 'list' object has no attribute 'transpose'

In [204]:
for i in range(len(country)):
    Country_name = country[i]
    g_medal = gold_medals[i]
    s_medal = silver_medals[i]
    b_medal = bronze_medals[1]
    total_medals = gold_medals +  silver_medals + bronze_medals
    t_medals = total_medals[i]
    print ('{} - {} gold medals, {} silver medals, {} bronze medals with a total of {}'.format(Country_name,g_medal,s_medal,b_medal,t_medals))
    

Great Britain - 29 gold medals, 17 silver medals, 22 bronze medals with a total of 65
China - 38 gold medals, 28 silver medals, 22 bronze medals with a total of 88
Russia - 24 gold medals, 25 silver medals, 22 bronze medals with a total of 81
United States - 46 gold medals, 28 silver medals, 22 bronze medals with a total of 103
Korea - 13 gold medals, 8 silver medals, 22 bronze medals with a total of 28
Japan - 7 gold medals, 14 silver medals, 22 bronze medals with a total of 38
Germany - 11 gold medals, 11 silver medals, 22 bronze medals with a total of 36
