In [1]:
# Bringing the SciPy function
from scipy.integrate import quad

In [2]:
# define the function 
def integrateFunction (x):
    return x

In [3]:
quad(integrateFunction,0,1)

(0.5, 5.551115123125783e-15)

In [8]:
5.551115123125783e-15*2

1.1102230246251565e-14

In [9]:
def integrateFn (x):
    return x*a+b

In [10]:
a=3
b=2


In [19]:
quad(integrateFn,0,1)

(3.5, 3.885780586188048e-14)

In [20]:
import scipy.integrate as integrate

In [23]:
# lambda is used to define region of integration 
def f(x,y):
    return x + y
integrate.dblquad(f,0,1,lambda x:0, lambda x: 2)

(3.0, 4.436070580899685e-14)

In [24]:
#optimization
import numpy as np
from scipy import optimize
def f(x):
    return x**2 + 5*np.sin(x) 

In [26]:
# using the optimize function with options displays the CONVERGENCE MESSAGES
minimaValue = optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [29]:
#minima value without options : no convergence messages, 
minimaValueWithoutOutput = optimize.minimize(f,x0=2,method='bfgs')
minimaValueWithoutOutput

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -3.2463942726915196
        x: [-1.111e+00]
      nit: 5
      jac: [-4.470e-07]
 hess_inv: [[ 1.545e-01]]
     nfev: 18
     njev: 9

In [31]:
import numpy as np 
from scipy.optimize import root 
def rootfunc(x):
    return x + 3.5 * np.cos(x)

In [34]:
rootValue = root(rootfunc, 0.3)

 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [-1.216e+00]
    nfev: 14
    fjac: [[-1.000e+00]]
       r: [-4.282e+00]
     qtf: [-8.329e-13]

In [35]:
rootValue

 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [-1.216e+00]
    nfev: 14
    fjac: [[-1.000e+00]]
       r: [-4.282e+00]
     qtf: [-8.329e-13]

In [42]:
# calculate eigenvalues and vectors
# import the required libraries
import numpy as np
from scipy import linalg

In [53]:
#test_data matrix -( rating on a scale of 1-10) ; linalg.eig
test_rating_data = np.array([[5,8],[7,9]])
eigenValues, eigenVector = linalg.eig(test_rating_data)
first_eigen, second_eigen = eigenValues

In [54]:
#print eigenvalues (1st and 2nd)
print (first_eigen, second_eigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [56]:
#print first eigenvector using slicing tech
print (eigenVector[:,0])

[-0.81220939  0.58336601]


In [57]:
#print second eigenvector using slicing tech
print (eigenVector[:,1])

[-0.63447346 -0.77294465]


In [1]:
34359748368 * 4398046511194

151115771435386135231392

In [3]:
import numpy as np
from scipy import linalg

test_rating_data = np.array([[14,23],[7,9]])
eigenValues, eigenVector = linalg.eig(test_rating_data)
first_eigen, second_eigen = eigenValues

In [4]:
print (first_eigen, second_eigen)

(24.432517156377564+0j) (-1.4325171563775627+0j)


In [5]:
#statistical sub-packages
from scipy.stats import norm

In [7]:
#rvs - random variables 
norm.rvs(loc=0, scale=1,size=10)

array([ 0.01998217,  0.88540942, -1.53178273, -1.30809388, -2.02730164,
        0.18519017,  0.10932818, -1.45159337, -0.02963744,  0.06063646])

In [8]:
norm.cdf(5,loc=1, scale=2)

0.9772498680518208

In [10]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18

In [11]:
#weave package inline() executes c++ code on the go, blitz () compiles all expressions to python. 


In [ ]:
#IO package. 

In [16]:
#using matrices for solving the equations
import numpy as np
from scipy import linalg
questionVaraible = ([[1,1],[4,9]])
totalVariable = ([30,150])
solution_for_x_y = linalg.solve(questionVaraible,totalVariable)

solution_for_x_y



array([24.,  6.])

In [24]:
#using scipy for random variable gneration
from scipy.stats import norm
norm.rvs(size = 20, loc = 0, scale =1)


array([-0.29875339,  1.48264461, -0.82725054,  0.50056458, -0.09638303,
       -0.38265638, -0.42939405,  1.19771001,  0.30500703, -1.2788778 ,
        1.25519826, -0.39189459, -1.60519135,  2.3827067 ,  1.76798291,
       -1.03493171,  0.08920574,  0.48882901, -0.93211426,  1.45626271])

In [27]:
#loc = 1, scale = 3
norm.cdf(10, loc = 1, scale =3)

0.9986501019683699

In [28]:
norm.pdf(14, loc = 1, scale =1)

7.998827757006813e-38